"""Models setup

Revision ID: 0c1efbbee064
Revises:
Create Date: 2021-01-28 15:37:13.108960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1efbbee064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('questionType', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr'),
    sa.UniqueConstraint('state')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1', sa.Integer(), nullable=True),
    sa.Column('user2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stateId', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['stateId'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userInterests',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('interestId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interestId'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestId', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['questionId'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['requestId'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialogueId', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('senderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialogueId'], ['dialogues.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('inPerson', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Boolean(), nullable=True),
    sa.Column('frequencyId', sa.Integer(), nullable=False),
    sa.Column('mentorship', sa.Boolean(), nullable=False),
    sa.Column('morning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['frequencyId'], ['frequencies.id'], ),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userExpertise',
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('expertiseId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertiseId'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['profileId'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profileId', 'expertiseId')
    )
    op.create_table('userLanguages',
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('languagesId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['languagesId'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['profileId'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profileId', 'languagesId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userLanguages')
    op.drop_table('userExpertise')
    op.drop_table('profiles')
    op.drop_table('messages')
    op.drop_table('answers')
    op.drop_table('userInterests')
    op.drop_table('requests')
    op.drop_table('locations')
    op.drop_table('dialogues')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('questions')
    op.drop_table('languages')
    op.drop_table('interests')
    op.drop_table('frequencies')
    op.drop_table('expertise')
    # ### end Alembic commands ###
