"""Create Interests Table

Revision ID: bafb9e1a4f48
Revises: 19e41e0ddf34
Create Date: 2021-01-25 20:05:42.402591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafb9e1a4f48'
down_revision = '19e41e0ddf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userInterests',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('interestId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interestId'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userInterests')
    op.drop_table('interests')
    # ### end Alembic commands ###
