"""empty message

Revision ID: 1efe7150d90e
Revises: 708508cd8a0f
Create Date: 2021-01-26 15:08:20.225415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efe7150d90e'
down_revision = '708508cd8a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('userExpertise',
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('expertiseId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertiseId'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['profileId'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profileId', 'expertiseId')
    )
    op.add_column('profiles', sa.Column('personality', sa.Boolean(), nullable=True))
    op.drop_column('profiles', 'projectInterest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('projectInterest', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'personality')
    op.drop_table('userExpertise')
    op.drop_table('expertise')
    # ### end Alembic commands ###
