"""empty message

Revision ID: 07f1974341a5
Revises: 1efe7150d90e
Create Date: 2021-01-26 15:18:58.487633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f1974341a5'
down_revision = '1efe7150d90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'title')
    # ### end Alembic commands ###
