"""Create Interest Tables

Revision ID: 52a631f397e9
Revises: d674c8fcb11e
Create Date: 2021-01-26 14:05:29.842234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a631f397e9'
down_revision = 'd674c8fcb11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userInterests',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('interestId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interestId'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userInterests')
    op.drop_table('interests')
    # ### end Alembic commands ###
