"""Create Profiles Tables

Revision ID: d401cd791909
Revises: 3545aed0f742
Create Date: 2021-01-26 14:04:14.587193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd401cd791909'
down_revision = '3545aed0f742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('inPerson', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('frequencyId', sa.Integer(), nullable=False),
    sa.Column('projectInterest', sa.String(), nullable=True),
    sa.Column('mentorship', sa.Boolean(), nullable=False),
    sa.Column('morning', sa.Boolean(), nullable=False),
    sa.Column('languagesId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frequencyId'], ['frequencies.id'], ),
    sa.ForeignKeyConstraint(['languagesId'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userLanguages',
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('languagesId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['languagesId'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['profileId'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profileId', 'languagesId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userLanguages')
    op.drop_table('profiles')
    op.drop_table('frequencies')
    # ### end Alembic commands ###
