"""Create Survey Tables

Revision ID: d674c8fcb11e
Revises: d401cd791909
Create Date: 2021-01-26 14:05:01.500178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd674c8fcb11e'
down_revision = 'd401cd791909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('questionType', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('requestId', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['questionId'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['requestId'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('requestId', 'questionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('requests')
    op.drop_table('questions')
    # ### end Alembic commands ###
