"""tables

Revision ID: ce368a7d79d0
Revises: 
Create Date: 2021-01-27 14:09:13.032319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce368a7d79d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_languagesId_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'languagesId')
    op.add_column('requests', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'title')
    op.add_column('profiles', sa.Column('languagesId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('profiles_languagesId_fkey', 'profiles', 'languages', ['languagesId'], ['id'])
    # ### end Alembic commands ###
